version: 2
jobs:
  build:
    docker:
      - image: maven:3.5.4-jdk-11
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Maven Build
          command: |
            VERSION="${CIRCLE_BUILD_NUM}"
            bin/build-jar.sh ${VERSION}
            JAR_NAME=pilger-suite-${VERSION}.jar
            mkdir artifact
            cp target/${JAR_NAME} artifact/
      - store_artifacts:
          path: artifact/pilger-suite-${VERSION}.jar
          destination: target
