version: 2
jobs:
  assemble:
    docker:
      - image: circleci/openjdk:11-jdk
    #        environment:
    #          FLASK_CONFIG: testing
    steps:
      - checkout
      - run: VERSION="${CIRCLE_BUILD_NUM}"
      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - maven-dependencies-
      - run:
          command: |
            VERSION="${CIRCLE_BUILD_NUM}"
            mvn "-Dversion=${VERSION}" dependency:resolve
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}
      - run:
          command: |
            VERSION="${CIRCLE_BUILD_NUM}"
            bin/pipeline-build-jar.sh ${VERSION}
      - store_artifacts:
          path: artifact
          destination: target
workflows:
  version: 2
  build_and_test:
    jobs:
      - assemble


