version: 2
jobs:
  build_jar:
    docker:
      - image: circleci/openjdk:11-jdk
    #        environment:
    #          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Build Docker
          command: |
            VERSION="${CIRCLE_BUILD_NUM}"
            bin/pipeline-build-jar.sh ${VERSION}
            setup_remote_docker
            bin/pipeline-build-docker.sh ${VERSION}
      - store_artifacts:
          path: artifact
          destination: target

