version: 2
jobs:
  build_jar:
    docker:
      - image: maven:3.5.4-jdk-11
    #        environment:
    #          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Maven Build
          command: |
            VERSION="${CIRCLE_BUILD_NUM}"
            bin/pipeline-build-jar.sh ${VERSION}
      - store_artifacts:
          path: artifact
          destination: target
  build_docker:
    docker:
      - image: docker
        environment:
          FLASK_CONFIG: testing
    steps:
      - run:
          name: Docker Build
          command: |
            VERSION="${CIRCLE_BUILD_NUM}"
            bin/pipeline-build-docker.sh ${VERSION}
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build_jar
      - build_docker:
          requires:
            - build_jar
