version: 2
jobs:
  build:
    docker:
      - image: maven:3.5.4-jdk-11
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Maven Build
          command: |
            VERSION="${CIRCLE_BUILD_NUM}"
            bin/build-jar.sh ${VERSION}
      - store_artifacts:
          path: target/pilger-suite-${VERSION}.jar
